Features/fragments
VadzimUrban/PokemonsInnowise pull request #10
Opened 2023-09-27 15:34 UTC by VadzimUrban

![activity_main](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/08924e6b-2039-4812-899c-1b52c8f67cdf)
![fragment_pokemon_detail](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/5e71576e-cf70-41a3-94b2-507b9a9a7c6e)
![fragment_pokemon_list](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/ac56e018-8fc2-4f5b-b975-3a1c2a3adabc)

сделал с использованием навигации, с использованием фрагмент менеджера буду делать на выходных

2023-10-02 08:33 UTC, pzinkevich42 requested changes

2023-10-02 08:33 UTC, pzinkevich42 commented on app/src/main/res/layout/fragment_pokemon_list.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Почему Recycler не может выступать в роли корневой вьюхи лейаута?

2023-10-02 08:33 UTC, pzinkevich42 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
используешь это где-то?

2023-10-04 20:46 UTC, pzinkevich42 requested changes

2023-10-04 20:46 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_main.xml
> +        <androidx.core.widget.NestedScrollView
Зачем тебе скроллить контейнер фрагментов?

2023-10-05 05:53 UTC, VadzimUrban commented on app/src/main/res/layout/activity_main.xml
> +        <androidx.core.widget.NestedScrollView
если не задать в NestedScrollView 
поведение (app:layout_behavior="@string/appbar_scrolling_view_behavior"), то список будет наезжать на апп бар. Хз может есть и другие варианты, но я нашёл этот

2023-10-09 16:36 UTC, pzinkevich42 approved these changes

2023-10-09 16:38 UTC, merged