Features/offline first app
VadzimUrban/PokemonsInnowise pull request #13
Opened 2023-10-24 11:22 UTC by VadzimUrban

плохо работает Т_Т

2023-10-26 14:15 UTC, pzinkevich42 requested changes

2023-10-26 14:15 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/localDB/PokemonDao.kt
>      fun getAllPokemons(): Flow<List<PokemonDataLocalDB>>
Обсуждали обновления

2023-10-26 14:15 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/remoteDB/responses/Result.kt
> +data class Result(
Лучше так конечно не называть модельки

2023-10-26 14:15 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/repository/ExtentionString.kt
> +    return id.reversed()
попроще конструкции нет?)

2023-10-26 14:15 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/repository/PokemonRepositoryImpl.kt
> +            // нарушение single responsibility мы получаем и записываем нужно исправить
нет, репозиторий занимается своим делом, управляет датасурсами и сам ничего не пишет.

2023-10-26 14:15 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonListFragment.kt
> +                        PokemonUiState(pokemons = emptyList()) ->
а что это за конструкция такая?

2023-10-26 14:40 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/localDB/PokemonDao.kt
>      fun getAllPokemons(): Flow<List<PokemonDataLocalDB>>
делал и так и так, когда на листах, то в реальном времени список не обновляет. Только поэтому оставил, как есть

2023-10-26 14:41 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/repository/ExtentionString.kt
> +    return id.reversed()
переделал через из диджитал)

2023-10-26 14:41 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/repository/PokemonRepositoryImpl.kt
> +            // нарушение single responsibility мы получаем и записываем нужно исправить
понял, принял, закрепил

2023-10-26 14:50 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonListFragment.kt
> +                        PokemonUiState(pokemons = emptyList()) ->
убрал, так как не имеет смысла, потому что по дефолту емпти лист

2023-10-26 14:53 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/remoteDB/responses/Result.kt
> +data class Result(
плагин назвал, а я согласился, переделал)

2023-10-31 19:36 UTC, VadzimUrban commented
![pokemon_list_item](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/1a47eac4-59f0-459c-88ce-7c981c21b039)
![activity_main](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/4513dcd2-db5e-479d-8877-63728f95a6a4)
![fragment_pokemon_detail](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/76a1a3aa-42d5-4824-8b68-bd0a59992d8c)
![fragment_pokemon_list](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/f3e0f212-ede1-4f4c-8cf2-42c70ac98129)
добавил картинки фрагментов и активити

2023-11-02 06:06 UTC, pzinkevich42 approved these changes

2023-11-02 07:08 UTC, merged