Features/list of pokemons
VadzimUrban/PokemonsInnowise pull request #7
Opened 2023-09-09 20:37 UTC by VadzimUrban

Homework #3
list of pokemons

2023-09-10 14:50 UTC, pzinkevich42 requested changes
Ответить на вопросы и исправить

2023-09-10 14:50 UTC, pzinkevich42 commented on README.md
> +### Current version: 1.0.0
Обычно поднятие версии и фича - разные вещи. Лучше такое разводить по разным ПРам

2023-09-10 14:50 UTC, pzinkevich42 commented on README.md
> +kotlin.plugin.serialization' version '1.9.10
форматирование поехало. да и можно просто обычным списком фигачить

2023-09-10 14:50 UTC, pzinkevich42 commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.10'
Кажется версию плагина можно вынести в проектный build.gradle

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
Между методами и/или полями надо бы пустую строчку оставлять для читаемости

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +        val pokemonsDataset = Datasource().toObject()
зачем переменная?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +    private val KG = " kg"
тут и выше - const

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +            val intent = Intent(it.context, MainActivity::class.java)
Получается ты не назад возвращаешься, а новое активити открываешь. Кажется тебе просто деталку закрыть надо

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +        val name = intent.getStringExtra("name")
1. Константы для Экстра, а то в одном месте по одним ключам складываешь, в друг - по другим достаёшь.
2. Почему не передавать объектом? Классы как раз созданы для объединения одних и тех же данных для более удобной работы с ними.
3. А что, если intent = null, или extra["name"] = null?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +        val height = intent?.getStringExtra("height") + CM
Для строк лучше использовать String::append(String)
Выглядит гораздо нагляднее, чем просто +
Также, кмк, гораздо нагляднее выглядит конструкция "${intent?.getStringExtra("height")} cm"

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +) : RecyclerView.Adapter<PokemonItemAdapter.PokemonItemViewHolder>() {
Есть дефолтный ListAdapter, почему написал его?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +    private val context: Context,
Зачем сохранять контекст? Это безопасно?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +    private val dataset: List<Pokemon>
dataset точно не будет изменятся?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +        var height = ""
почему в одних переменных ссылки на вьюхи, а в других - значения?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +        holder.fullCard.setOnClickListener {
Если уж начал использовать ресайклер, то давай делать его до конца. Холдер не должен обрабатывать клики. Клик должен выставляться при инициализации адаптера "снаружи". Интент также не должен тут формироваться. Тогда и контекст тебе не понадобится

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/Datasource.kt
> +    fun toObject (): List<Pokemon> {
Название toObject подразумевает преобразование конкретного объекта в "Object". Но он и так Object, получается каша.
В твоём случае, у тебя класс создаёт данные, то есть createDatasource. Но чтобы не было datasource.createDatasource(), я бы сделал datasource.create() / datasource.get()

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/Datasource.kt
> +const private val DATA = """
private const val

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/model/PokemonDetail.kt
> +    @StringRes val name: Int,
У тебя все имена покемонов лежат в ресурсах? Зачем эти аннотации?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/data.json
Зачем этот файл нужен?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/model/PokemonsDataClass.kt
> +data class PokemonsDataClass(
Зачем в названии класса писать, что это DataClass? Какое предназначение у этого класса?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/model/PokemonsDataClass.kt
> +import androidx.annotation.DrawableRes
Точно используешь?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/drawable/andre_the_giant.xml
зачем тебе картинки покемонов локально?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/drawable/blastoise.png
png - слишком объёмный ресурс. webp лучше

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_main.xml
> +        android:scrollbars="vertical"
может orientation?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
что?

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        app:layout_constraintHorizontal_bias="0"
Зачем? Если ты используешь байас, то у тебя что-то не так с констреинтами скорее всего

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
авыправып

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
впававапв

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
вапвап

2023-09-10 14:50 UTC, pzinkevich42 commented on app/src/main/res/layout/pokemons_list_item.xml
> +    android:layout_marginEnd="16.dp"
точка?

2023-09-10 16:00 UTC, VadzimUrban commented on README.md
> +### Current version: 1.0.0
Т.е. следующим этапом смержить, с дева создать ветку релиза и опять пул реквестом тоже самое скинуть?

2023-09-10 16:01 UTC, VadzimUrban commented on README.md
> +kotlin.plugin.serialization' version '1.9.10
исправлю

2023-09-10 16:05 UTC, VadzimUrban commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.10'
можно или нужно ?) Исправил

2023-09-10 16:06 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
там визуально, была, но это от гита обманка, исправил

2023-09-10 16:10 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +        val pokemonsDataset = Datasource().toObject()
ниже, 21 строка pokemonList.adapter принимает функцию с аргументом dataset.  Для этого)

2023-09-10 16:13 UTC, VadzimUrban commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        app:layout_constraintHorizontal_bias="0"
не записал сходу ширину 0dp, и без веса не занимала нужное положение. Забыл удалить, уже удалил.

2023-09-10 16:16 UTC, VadzimUrban commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
насколько я помню, поле обязательное в этой вьюхе. Могу через string, что-то добавить, но не вижу разницы. Если принято так, то сделаю без проблем)

2023-09-10 16:16 UTC, VadzimUrban commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
насколько я помню, поле обязательное в этой вьюхе. Могу через string, что-то добавить, но не вижу разницы. Если принято так, то сделаю без проблем)

2023-09-10 16:16 UTC, VadzimUrban commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
насколько я помню, поле обязательное в этой вьюхе. Могу через string, что-то добавить, но не вижу разницы. Если принято так, то сделаю без проблем)

2023-09-10 16:17 UTC, VadzimUrban commented on app/src/main/res/layout/pokemons_list_item.xml
> +    android:layout_marginEnd="16.dp"
из композа привычка, убрал.

2023-09-10 16:24 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +    private val KG = " kg"
это ещё утром поменял)

2023-09-10 16:25 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +            val intent = Intent(it.context, MainActivity::class.java)
Да, я делал по описанной тобой логике, а нужно просто finish() ?

2023-09-10 16:31 UTC, VadzimUrban commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.10'
поменял, не работает, в app нужно

2023-09-10 16:33 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +            val intent = Intent(it.context, MainActivity::class.java)
пробнул, прикольно)

2023-09-10 16:53 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +        val name = intent.getStringExtra("name")
1. Сделал, отличное замечание.
2. Согласен полностью. Я бы хотел, но не получилось, фича следующей версии будет).
3. Понял, переделаю.

2023-09-10 17:02 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/PokemonDetailActivity.kt
> +        val height = intent?.getStringExtra("height") + CM
мне мой вариант, больше нравится, но раз нужно, выбрал 3)

2023-09-10 17:08 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +    private val context: Context,
вот это хз, в примере так было. Самое интересное студия говорит, что нигде не используется)

2023-09-10 17:18 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +    private val dataset: List<Pokemon>
на данном этапе не будет, а как с бэка буду грузить, то может меняться

2023-09-10 17:19 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +) : RecyclerView.Adapter<PokemonItemAdapter.PokemonItemViewHolder>() {
не знал, опять же с примера, не углубился в ресайклервью

2023-09-10 17:22 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +        var height = ""
потому что в pokemons_list_item.xml у меня нету таких полей.

2023-09-10 17:32 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/Datasource.kt
> +const private val DATA = """
исправил

2023-09-10 17:33 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/Datasource.kt
> +    fun toObject (): List<Pokemon> {
исправил, хорошее замечание

2023-09-10 17:33 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/data.json
удалил

2023-09-10 17:37 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/model/PokemonDetail.kt
> +    @StringRes val name: Int,
лежали до того, как json скинул, счас 2 файла этих не используются. И из ресурсов удалил.

2023-09-10 17:38 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/model/PokemonsDataClass.kt
> +import androidx.annotation.DrawableRes
Удалил, были попытки схитрить, но не получилось)

2023-09-10 17:41 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/model/PokemonsDataClass.kt
> +data class PokemonsDataClass(
Хотел список сразу передавать дата классом, но передумал. Удалил.

2023-09-10 17:43 UTC, VadzimUrban commented on app/src/main/res/drawable/andre_the_giant.xml
потому что на данном этапе не умею загружать с бэка, до ретрофит не дошел. Тоже самое, что и зачем мне дата локально) Это временно.

2023-09-10 17:47 UTC, VadzimUrban commented on app/src/main/res/drawable/blastoise.png
знаю, но какие были на гитхабе)

2023-09-10 17:49 UTC, VadzimUrban commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
не понял)

2023-09-10 17:50 UTC, VadzimUrban commented on app/src/main/res/layout/activity_main.xml
> +        android:scrollbars="vertical"
поменял)

2023-09-12 18:58 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +        holder.fullCard.setOnClickListener {
исправил

2023-09-13 18:21 UTC, pzinkevich42 commented on README.md
> +### Current version: 1.0.0
Конкретно повышение версии по разному может быть реализовано. Например, да, этот ПР мерджится (без изменения версии), отводится релиз, в него мерджится ПР с поднятием версии до `1.0.0` и вешается тег `v1.0.0-rc`, после влития в мастер на мердж комит вешается тег `v1.0.0` и вливается в дев, таким образом изменение версии в билд-файле и ридми попадёт и в дев.

2023-09-13 18:26 UTC, pzinkevich42 commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.10'
корневой `build.gradle` :
`    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.10' apply false`
модульный `build.gradle`:
`    id 'org.jetbrains.kotlin.plugin.serialization'`
и всё работает

2023-09-13 18:28 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +        val pokemonsDataset = Datasource().toObject()
а не пихать результат в переменную, а сразу запихнуть его как аргумент?)

2023-09-13 18:30 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +    private val context: Context,
значит он тебе не нужен)

2023-09-13 18:31 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +    private val dataset: List<Pokemon>
так может сразу и сделать его var

2023-09-13 18:31 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonItemAdapter.kt
> +        var height = ""
а зачем их тогда сохранять?

2023-09-13 18:33 UTC, pzinkevich42 commented on app/src/main/res/drawable/blastoise.png
студия умеет автоматически конвертировать в webp

2023-09-13 18:33 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
я тоже, давай не будем писать тарабарщину

2023-09-13 18:34 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
если значение задаётся из кода - то ничего не надо писать в разметке

2023-09-13 18:34 UTC, pzinkevich42 commented
Если написано, что исправил - должны быть исправления. Пока не нашёл

2023-09-13 20:43 UTC, VadzimUrban commented on app/src/main/res/drawable/blastoise.png
исправил, прикольная штука, не знал)

2023-09-13 20:43 UTC, VadzimUrban commented on app/src/main/res/layout/activity_pokemon_detail.xml
> +        android:text="dsfsdfsdf"
исправил заглушкой

2023-09-14 20:38 UTC, pzinkevich42 requested changes
Давай добьём этот ПР и сделаем красиво

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this@MainActivity)
кажется это в xml лучше и удобнее задавать

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +            val intent = Intent(this, PokemonDetailActivity::class.java)
обсудили, что лучше одним классом и в `PokemonDetailActivity`

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +    var onPokemonClick: ((Pokemon) -> Unit)? = null
Можно не `null`, а пустой метод `{ }`, чтобы избавиться от нулабельности

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +                "1" -> photo.setImageResource(R.drawable.bulbasavr)
ну вот можно же положить ссылку на ресурс в pokemonData

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +        var id = ""
зачем тебе всё это сохранять?

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +        var photo = binding.photo
можно один биндинг сохранить

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/data/Datasource.kt
> +    fun create (): List<Pokemon> {
Перед скобочками не ставится пробел:
`fun create(): List<Pokemon> {`

2023-09-14 20:38 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this@MainActivity)
И задаёшь же в xml. Надо убрать дублирование отсюда.

2023-09-15 09:01 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +            layoutManager = LinearLayoutManager(this@MainActivity)
Тоже думал об этом, зачем в 2 местах. Убрал.

2023-09-15 09:01 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +    var onPokemonClick: ((Pokemon) -> Unit)? = null
Поменял

2023-09-15 09:02 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/data/Datasource.kt
> +    fun create (): List<Pokemon> {
Уже нету, промазал видимо)

2023-09-16 09:58 UTC, pzinkevich42 commented
Замечания по этому ПР надо поправлять в этом ПР. Ты пишешь, что исправил, но я этого не вижу

2023-09-16 10:02 UTC, VadzimUrban commented
> Замечания по этому ПР надо поправлять в этом ПР. Ты пишешь, что исправил, но я этого не вижу

Я ещё не пушил

2023-09-16 10:24 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +                "1" -> photo.setImageResource(R.drawable.bulbasavr)
Не получилось

2023-09-16 10:26 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +        var id = ""
Чтобы передать в детэйл, у меня нету вьюшек под эти данные в мэйн активити, поэтому просто биндингом не получится

2023-09-16 10:26 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +            val intent = Intent(this, PokemonDetailActivity::class.java)
Не получилось тоже

2023-09-16 10:36 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/adapter/PokemonAdapter.kt
> +        var photo = binding.photo
Сделал

2023-09-16 15:57 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
> +            val intent = Intent(this, PokemonDetailActivity::class.java)
Получилось)

2023-09-23 10:20 UTC, merged