Features/ca
VadzimUrban/PokemonsInnowise pull request #8
Opened 2023-09-16 14:15 UTC by VadzimUrban

закончил CA

2023-09-18 14:58 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/repository/PokemonRepositoryImpl.kt
> +        return DomainMapper().mapToDomain(pokemonDataList)
```suggestion
        return mapper.mapToDomain(pokemonStorage.getPokemonList())
```

2023-09-18 19:51 UTC, pzinkevich42 commented
Мы прошлый ПР будем вливать перед этим?

2023-09-18 20:09 UTC, VadzimUrban commented
> Мы прошлый ПР будем вливать перед этим?

Я бы не вливал, нафиг он нужен, захламлять только)

2023-09-19 21:52 UTC, pzinkevich42 requested changes

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
переносом не получилось?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +    lateinit var viewModel: MainViewModel
`private` ?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +    private val pokemonAdapter = PokemonDiFactory.createPokemonAdapter()
Адаптеры обычно не кладут в DI, а создают по месту, так как у них нет и не должно быть внешних зависимостей

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +    lateinit var viewModel: MainViewModel
```suggestion
    private val viewModel: MainViewModel by viewModels()
```
Делегат `viewModels()` доступен в библиотеках `activity-ktx` и `fragment-ktx` для необходимых классов соответственно в рамках Jetpack и с параметрами конструктора для DI в случае с Hilt

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +        }
```suggestion
        binding.pokemonDomainList.adapter = pokemonAdapter
```

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +        })
```suggestion
        viewModel.pokemonList.observe(this) {
            pokemonAdapter.submitList(it)
        }
```

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +        viewModel.getList()
На сколько я понимаю, адаптеру в конструкторе скармливается список данных, а потом обновляется таким же через лайвдату. Кажется одно из двух действий лишнее

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainViewModel.kt
> +    val getPokemonListUseCase: GetPokemonListUseCase
вот чтобы с фабрикой для VM не мучаться, можно создать переменную и проинициализировать через DI

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainViewModelFactory.kt
> +    private val getPokemonListUseCase = PokemonDiFactory.createPokemonList()
Вот тут всё равно тянемся в DI, зачем же тогда фабрика?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +            nameDetailMore.text = dataFromMainActivity?.name ?: "Name not found"
Получается, если данных для деталки нет, ты 4 раза проверяешь что их нет при помощи `?.`. Внутреннее чувство прекрасного и капелька перфекционизма по отношению к коду заставляют задуматься в этом моменте.

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +            when (nameDetailMore.text) {
вьюха ненадёжный источник данных и для этого не предназначена. Данные у тебя хранятся в соответствующей переменной, которую необходимо использовать по её назначению

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +                "Butterfree" -> binding.photoDetail.setImageResource(R.drawable.butterfree)
может вынести это в отдельную функцию? `mapPokemonNameToDrawableRes`

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +class PokemonAdapter(private val pokemonDomainList: List<com.example.domain.models.PokemonDomain>) : ListAdapter<PokemonDomain, PokemonAdapter.PokemonViewHolder>(
В ListAdapter уже есть способ хранения данных, дублировать их в переменную не надо, тем более в конструкторе

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        var weight = ""
Зачем тебе эти премененные?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +                "11" -> binding.photo.setImageResource(R.drawable.metapod)
Где-то я уже такую схемку видел...

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +                else -> binding.photo.setImageResource(R.drawable.butterfree)
Для id=12,13,14,... один ресурс?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +            return areItemsTheSame(oldItem, newItem)
Кажется смысл этих методов немного в другом

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +            onPokemonClick.invoke(currentPokemon)
```suggestion
            onPokemonClick(currentPokemon)
```

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        holder.bindData(getItem(position))
```suggestion
        val currentPokemon = getItem(position)
        holder.bindData(currentPokemon)
```

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        val binding =
Можно ли тут обойтись без переменной?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/di/PokemonDiFactory.kt
> +    fun createPokemonList() = GetPokemonListUseCase(PokemonRepositoryImpl(PokemonStorageImpl()))
название метода не соответствует происходящему внутри

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_main.xml
Договорились прикладывать скриншоты экранов к изменениям в разметке

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/res/values/strings.xml
> +    <string name="stub_text">stub text</string>
И что этот текст делает?

2023-09-19 21:52 UTC, pzinkevich42 commented on app/src/main/res/values/strings.xml
> +    <string name="empty_image_description"> </string>
Зачем это нужно?

2023-09-19 21:52 UTC, pzinkevich42 commented on data/build.gradle
Всё ли в этом файле ты используешь?

2023-09-19 21:52 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/models/PokemonData.kt
> +                       val weight: String)
С форматированием всё ок?

2023-09-19 21:52 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/repository/DomainMapper.kt
> +    fun mapToDomain(pokemonDataList: List<PokemonData>): List<PokemonDomain> {
Я не призываю пихать везде где можно экстеншены и мапперы часто на них делают, поэтому тут выбор за тобой

2023-09-19 21:52 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/storage/PokemonStorage.kt
> +interface PokemonStorage {
Не лишний интерфейс?

2023-09-19 21:52 UTC, pzinkevich42 commented on domain/build.gradle
> +    id 'java-library'
Жёсткое ограничение. Может android-library ?

2023-09-19 21:52 UTC, pzinkevich42 commented on domain/src/main/java/com/example/domain/models/PokemonDomain.kt
> +) : Serializable
`java.io.Serializable` имеет какое-то отношение к доменной области?

2023-09-19 21:52 UTC, pzinkevich42 commented on domain/src/main/java/com/example/domain/usecase/GetPokemonListUseCase.kt
> +class GetPokemonListUseCase(private val pokemonRepository: PokemonRepository) {
Ну можно интерактор, чтобы не плодить миллиард однострочных юзкейсов

2023-09-19 21:52 UTC, pzinkevich42 commented on settings.gradle
> +include ':domain'
Вообще многомодульность используют для разделения на фичи, а не на слои. Но в данном случае дело за тобой.

2023-09-20 10:53 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
У меня всё норм, в presentation находится

2023-09-20 10:54 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +    lateinit var viewModel: MainViewModel
Сделал

2023-09-20 10:56 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +    private val pokemonAdapter = PokemonDiFactory.createPokemonAdapter()
Принял, убрал.

2023-09-20 11:28 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +        viewModel.getList()
я конечно не эксперт, но у тебя тоже самое в проекте

2023-09-20 11:29 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +    lateinit var viewModel: MainViewModel
спасибо, поменял

2023-09-20 11:30 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +        })
поменял

2023-09-20 11:41 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainViewModelFactory.kt
> +    private val getPokemonListUseCase = PokemonDiFactory.createPokemonList()
убрал

2023-09-20 11:45 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +            nameDetailMore.text = dataFromMainActivity?.name ?: "Name not found"
если правильно понял, перед интент поставить ? 

сделал

2023-09-20 11:48 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +                else -> binding.photo.setImageResource(R.drawable.butterfree)
это финальный список, я больше добавлять не буду, поэтому корректно

2023-09-20 11:51 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +            return areItemsTheSame(oldItem, newItem)
изменил на полную проверку

2023-09-20 11:52 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +            onPokemonClick.invoke(currentPokemon)
убрал

2023-09-20 11:55 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        holder.bindData(getItem(position))
поменял

2023-09-20 11:55 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/di/PokemonDiFactory.kt
> +    fun createPokemonList() = GetPokemonListUseCase(PokemonRepositoryImpl(PokemonStorageImpl()))
поменял

2023-09-20 11:56 UTC, VadzimUrban commented on app/src/main/res/values/strings.xml
> +    <string name="stub_text">stub text</string>
убрал, был как заглушка

2023-09-20 11:56 UTC, VadzimUrban commented on app/src/main/res/values/strings.xml
> +    <string name="empty_image_description"> </string>
убрал, был как заглушка

2023-09-20 11:57 UTC, VadzimUrban commented on domain/src/main/java/com/example/domain/models/PokemonDomain.kt
> +) : Serializable
да, как эту модельку достаю в детэйл вью

2023-09-20 11:58 UTC, VadzimUrban commented on domain/src/main/java/com/example/domain/usecase/GetPokemonListUseCase.kt
> +class GetPokemonListUseCase(private val pokemonRepository: PokemonRepository) {
вот тут интересный момент, т.к. я думал, что в этом и заключается философия "один класс - один метод"

2023-09-20 11:59 UTC, VadzimUrban commented on settings.gradle
> +include ':domain'
мне понравилось, что можешь поставить ограничение функций на модуль, сокращает ошибки

2023-09-20 13:49 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/MainActivity.kt
> +        viewModel.getList()
после глубочайшего анализа, понял, что был неправ )
удалил из конструктора адаптера

2023-09-20 13:59 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +class PokemonAdapter(private val pokemonDomainList: List<com.example.domain.models.PokemonDomain>) : ListAdapter<PokemonDomain, PokemonAdapter.PokemonViewHolder>(
убрал

2023-09-20 14:02 UTC, VadzimUrban commented on data/src/main/java/com/example/data/models/PokemonData.kt
> +                       val weight: String)
форматнул)

2023-09-20 14:06 UTC, VadzimUrban commented on domain/build.gradle
> +    id 'java-library'
я же тут только с котлином буду работать, зачем андроид?

2023-09-20 14:11 UTC, VadzimUrban commented on data/build.gradle
с андроидом вообще не работаю и пока хз буду-ли в будущем

2023-09-20 14:13 UTC, VadzimUrban commented on data/src/main/java/com/example/data/storage/PokemonStorage.kt
> +interface PokemonStorage {
опять же согласно философии должны с интерфейса начинать или я не так понял?

2023-09-20 14:20 UTC, VadzimUrban commented on data/src/main/java/com/example/data/repository/DomainMapper.kt
> +    fun mapToDomain(pokemonDataList: List<PokemonData>): List<PokemonDomain> {
поменял на функцию со скоуп

2023-09-20 14:22 UTC, VadzimUrban commented on app/src/main/res/layout/activity_main.xml
не вижу где в комменте приложить

2023-09-20 14:24 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        val binding =
убрал

2023-09-20 14:43 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        var weight = ""
чтобы перекинуть в детэйл вью

2023-09-20 14:48 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +            when (nameDetailMore.text) {
поменял

2023-09-20 14:48 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/adapter/PokemonAdapter.kt
> +        var weight = ""
понял жизнь, они нафиг не нужны ха )
удалил

2023-09-20 18:01 UTC, pzinkevich42 commented on domain/src/main/java/com/example/domain/usecase/GetPokemonListUseCase.kt
> +class GetPokemonListUseCase(private val pokemonRepository: PokemonRepository) {
А где ты слышал про философию "один класс - один метод"?

2023-09-20 18:06 UTC, pzinkevich42 commented on domain/src/main/java/com/example/domain/models/PokemonDomain.kt
> +) : Serializable
Я не слышал, чтобы у Покемонов была такая возможность как сериализация (если не считать конечно покебол). Также не слышал, чтобы у Покемонов была какая-то детейл вью.

Я это к тому, что твои проблемы передачи файлов не касаются бизнес-логики. Если завтра я скажу переделать способ передачи данных между экранов на Parcelize, ты пойдёшь что-то менять в доменной области с бизнес-логикой

2023-09-20 18:10 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/storage/PokemonStorage.kt
> +interface PokemonStorage {
Интерфейс предполагает:
1. либо несколько реализаций
2. либо помогает разобраться с зависимостями, что приводит к реализации пункта 1
Таким образом не должно быть интерфейсов с одной реализацией. Пусть и с потенциально существующими. В данном случае я не вижу появления второго вида Стораджа Покемонов. Все возможные БД или Сеть разруливаются через Репозиторий

2023-09-20 18:16 UTC, pzinkevich42 commented on app/src/main/res/layout/activity_main.xml
![скриншот](https://github.com/VadzimUrban/PokemonsInnowise/assets/143994239/a1d2a09f-2fd5-4ed7-941c-9a995e06a8af)

2023-09-20 18:17 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/MainActivity.kt
Ну а тут нет, значит похерится история изменений исходного файла

2023-09-20 18:28 UTC, pzinkevich42 requested changes

2023-09-20 18:28 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +            nameDetailMore.text = dataFromMainActivity?.name ?: "Name not found"
Идея в том, чтобы в коде максимально быстро отказываться от нуллабельности везде, где это возможно. В твоём случае, проверив сразу интент и наличие данных, в случае их отсутствия ты можешь вызвать один метод установки пустых значений сразу во все поля, т.н. Empty View, а в случае, если значение есть - то сразу сохранить его в переменную с не нулабельным типом.

2023-09-20 18:28 UTC, pzinkevich42 commented on app/src/main/java/com/example/pokemonsinnowise/presentation/getPhoto.kt
> +internal fun getPhoto(name: String?) = when (name) {
Может без нулабельности?

2023-09-20 18:28 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/repository/mapper.kt
> +}
```suggestion
fun List<PokemonData>.mapToDomain(pokemonDataList: List<PokemonData>): List<PokemonDomain> {
    return map {
        PokemonDomain(it.id, it.photo, it.name, it.type, it.height, it.weight)
    }
}
```

2023-09-20 19:31 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/repository/mapper.kt
> +}
И заменить `{ return ... }` на ` = ...`

2023-09-21 06:16 UTC, VadzimUrban commented on data/src/main/java/com/example/data/repository/mapper.kt
> +}
изменил. Это я так понимаю для реюзабельности ?

2023-09-21 06:41 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/PokemonDetailActivity.kt
> +            nameDetailMore.text = dataFromMainActivity?.name ?: "Name not found"
Если правильно понял, то сделал по инструкции )

2023-09-21 06:42 UTC, VadzimUrban commented on app/src/main/java/com/example/pokemonsinnowise/presentation/getPhoto.kt
> +internal fun getPhoto(name: String?) = when (name) {
убрал

2023-09-21 06:44 UTC, VadzimUrban commented on data/src/main/java/com/example/data/storage/PokemonStorage.kt
> +interface PokemonStorage {
окей, я думал, что через сторадж будет Сеть.

2023-09-21 06:53 UTC, VadzimUrban commented on domain/src/main/java/com/example/domain/models/PokemonDomain.kt
> +) : Serializable
идею понял, проблему не решил

2023-09-21 06:56 UTC, VadzimUrban commented on domain/src/main/java/com/example/domain/usecase/GetPokemonListUseCase.kt
> +class GetPokemonListUseCase(private val pokemonRepository: PokemonRepository) {
single responsibility, не ? интерактор будет за несколько экранов отвечать, например. Или я что-то не догоняю

2023-09-21 19:42 UTC, VadzimUrban commented
> скриншоты для проверки вёрстки

![MainActivity](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/8d3a6d50-b393-46d4-9ada-d0c267e62984)
![PokemonDetail](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/3f995bfb-6084-4a09-89cb-0a839a7a1865)
![PokemonItem](https://github.com/VadzimUrban/PokemonsInnowise/assets/104270322/1259e61f-3ee5-4294-9f45-57d69e385346)
Готов к релизу =)

2023-09-22 18:56 UTC, pzinkevich42 commented on data/src/main/java/com/example/data/repository/mapper.kt
> +}
Это для кодстайла

2023-09-22 19:03 UTC, pzinkevich42 approved these changes

2023-09-23 10:20 UTC, merged